CREATE TABLE IF NOT EXISTS resources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT NOT NULL,       -- ROOM, LAB, EQUIPMENT
    capacity INTEGER NOT NULL,
    active BOOLEAN DEFAULT 1
);
